### ISSUE TITLE
Inheritance problem - saving EventData objects

### ISSUE THREAD

**Issue by psiabeta** [Quivr/iOS-Week-View#11]
I'm having another hard time with the library as I cannot save `EventData` objects (Realm, CoreData).
To be able to store events, `EventData` has to inherit from Object (Realm) or NSObject (CoreData), what makes redundant conformance to `CustomStringConvertible, Equatable, Hashable` protocols:

<img width="877" alt="zrzut ekranu 2018-06-29 o 16 09 41" src="https://user-images.githubusercontent.com/39163036/42096936-ff5e7f1a-7bb6-11e8-9f40-2d23f9ce4bf4.png">

But even if I remove 3 protocols mentiones above, I'm still getting about 12 errors, like:

> Initializer 'init(id:title:startDate:endDate:location:color:)' with Objective-C selector 'initWithId:title:startDate:endDate:location:color:' conflicts with previous declaration with the same Objective-C selector

> Method 'configureGradient' with Objective-C selector 'configureGradient:' conflicts with previous declaration with the same Objective-C selector

and so on...:

<img width="1352" alt="zrzut ekranu 2018-06-29 o 16 13 05" src="https://user-images.githubusercontent.com/39163036/42097053-57ff9c8a-7bb7-11e8-9527-9c759a57eb13.png">

the question is... how do you store them !? I'm going out of my head trying to find out how to add events to my Realm / CoreData database.

Could you give me a hint, please?

**Comment by reilem** [comment]
I'm afraid I don't know how fix your exact problem. A work around you could consider is trying to make a separate class which could act as a storage proxy and contains fields for all the data you want to save persistently. You can then store those objects using Realm / CoreData and after fetching them convert them back to EventData objects.

Again, this is most definitely not an elegant fix but it might work. I'll have a look if I can make the EventData inherit from Object.

**Comment by psiabeta** [comment]
Thank you for your reply. Well I'll give it a try to write some converters as you suggest, but I'm affraid it's going to be memory consuming. Please let me know whether (or not) you will be able to make any changes to EventData. I believe it would be a fantastic upgrade for all other users :)

By the way thank you for all your hard work with both iOS and Android versions!

**Comment by reilem** [comment]
Hi @psiabeta, after all this time I have finally managed to fix this issue. I think some of the new swift/XCode updates made it doable. The PR #25 will be merged and released soon.
