### ISSUE TITLE
Event time print

### ISSUE THREAD

**Issue by clbemre** [Quivr/iOS-Week-View#13]
How to remove event default time text. I want to display just event data title.
<img width="70" alt="Ekran Resmi 2019-04-01 13 57 43" src="https://user-images.githubusercontent.com/7671284/55322913-3a2eb080-5486-11e9-8566-cdca1bb9a3a9.png">

**Comment by reilem** [comment]
Usually you can subclass EventData and modify the `getDisplayString` function. You can then pass these events to the WeekView.

**Comment by clbemre** [comment]
Okey, thank you very much 🙏
