### ISSUE TITLE
Remove All Events Not Work!!

### ISSUE THREAD

**Issue by clbemre** [Quivr/iOS-Week-View#14]
self.allCalendarEvents.removeAll()
self.calendarWeekView.loadEvents(withData: nil)

Why are the events still displayed?

**Comment by reilem** [comment]
If you pass a `nil` object then no action is performed, this is intended behaviour to allow for default functions to pass `nil` objects safely without harming the state of the weekview. You must pass an empty array to remove all events. If that doesn't work then something may indeed be broken.

**Comment by clbemre** [comment]
Okey thank you sir:)
