### ISSUE TITLE
How to custom event view?

### ISSUE THREAD

**Issue by clbemre** [Quivr/iOS-Week-View#15]
Shadow,Corner Radius and Center Title?

**Comment by reilem** [comment]
These customisation features haven't been added yet. I don't immediately have time to implement these but feel free to give it a go yourself :)

**Comment by clbemre** [comment]
So, how? :)

**Comment by stomper3579** [comment]
Did you ever find out how to add a corner radius?  I've been unsuccessful so far :(

**Comment by clbemre** [comment]
No, im sorry :)

**Comment by reilem** [comment]
I have added a `eventStyleCallback` property that you can use to access the each event layer and customise it your hearts content.
If you wish to access the text layer then you can iterate over the sublayers of the `CALayer` until you find a `CATextLayer`, this you can also customise, or even remove and add your own.

**Comment by reilem** [comment]
Closing, since this is now solved :)
