### ISSUE TITLE
Error display event?

### ISSUE THREAD

**Issue by clbemre** [Quivr/iOS-Week-View#17]
<img width="331" alt="Screen Shot 2019-07-31 at 11 19 14" src="https://user-images.githubusercontent.com/7671284/62195641-1c664f00-b385-11e9-8142-7b9819224b8c.png">

why doesn't it cover all days ?

**Comment by reilem** [comment]
This is done on purpose to display the events in a more compact way. I could add a customization flag to disable this behaviour if you want. :)

**Comment by clbemre** [comment]
Yes i want :) like this image
![Screenshot_20190731_221207](https://user-images.githubusercontent.com/7671284/62241053-13a36680-b3e1-11e9-9f16-29a00dc3a7cc.jpg)

**Comment by clbemre** [comment]
??

**Comment by reilem** [comment]
Sorry for the delay. I’ll implement this when I have time. If you want you can always make a PR to add it yourself. 😁

**Comment by reilem** [comment]
Alright so in `0.13.0` there is a `autoConvertAllDayEvents` flag. Just set it to `false` and you should get what you are looking for. Let me know if there are any issues with it.

**Comment by clbemre** [comment]
Oh thank you i will try 🙏🏻

**Comment by clbemre** [comment]
Hey great! thank you so much :)

<img width="350" alt="Screen Shot 2019-08-26 at 13 52 31" src="https://user-images.githubusercontent.com/7671284/63685757-d7f59400-c808-11e9-85b9-2d92b7b5c442.png">

**Comment by reilem** [comment]
Glad I could help 😄
