### ISSUE TITLE
Is it possible to turn off the infinite horizontal scroll

### ISSUE THREAD

**Issue by AryaaSk** [Quivr/iOS-Week-View#20]
I just wanted to know if it was possible to turn off the horizontal scroll as in my project I only need it for one day at a time

**Comment by reilem** [comment]
This is currently not supported, but I think it'll be easy to implement so I might give it a go. Will let you know when it's done.

**Comment by AryaaSk** [comment]
> This is currently not supported, but I think it'll be easy to implement so I might give it a go. Will let you know when it's done.

Thank you please let me know by just responding here

**Comment by reilem** [comment]
Finite scrolling is implemented in PR #26 this issue will close automatically when it is merged. If you have any other comments, feel free to open another issue 😄
