### ISSUE TITLE
How to store events

### ISSUE THREAD

**Issue by AryaaSk** [Quivr/iOS-Week-View#21]
I just wanted to know if there was an easy way to store the event data on the iPhone or in a database so when the app is closed and re-opened it still contains all the same events as before. 

Just to clarify I want to know how to store the event data for the calendar with all the events I have created, and how I would load the events in with viewDidLoad()

**Comment by reilem** [comment]
Someone else had a similar issue #11, that was a bit of a dead end. Our react-native apps usually persist the events as JSONs in a string. However, I'll admit this isn't a great solution for a native app.

You're in luck though, I have some time on my hands and plan on fixing a few things tomorrow. So I will take a look at this issue while I'm at it. I'll update the README with instructions for event persistence if I find a solution.

**Comment by reilem** [comment]
I have fixed this issue in PR #25, which will be merged and released soon.
