### ISSUE TITLE
Cannot update new cocoapod 

### ISSUE THREAD

**Issue by AryaaSk** [Quivr/iOS-Week-View#27]
I have tried updating to your new update for the finite scrolling but it does not allow me to
It gives me this error

[!] Error installing QVRWeekView
[!] /usr/bin/git clone https://github.com/Quivr/iOS-Week-View.git /var/folders/n3/4b_44kjd1s38037nwq8hv67c0000gp/T/d20200516-8075-1uika7r --template= --single-branch --depth 1 --branch 0.14.0
Cloning into '/var/folders/n3/4b_44kjd1s38037nwq8hv67c0000gp/T/d20200516-8075-1uika7r'...
warning: Could not find remote branch 0.14.0 to clone.
fatal: Remote branch 0.14.0 not found in upstream origin

**Comment by reilem** [comment]
Oh dear, I must have messed up the tags when I made the release `v0.14.0` and removed the old tag `0.14.0`. I have re-uploaded with a fixed tag, and you should be able to download a version `0.14.1`. I hope this fixes the problem. Thank you so much for letting me know!
