### ISSUE TITLE
grey gap when scrolling

### ISSUE THREAD

**Issue by ezmegy** [Quivr/iOS-Week-View#3]
Hi,

There's a fairly big blank (grey) area on the top and also at the bottom when scrolling the weekview.
[See screensot.](https://drive.google.com/open?id=0B5UFlCWAEL50d1NZdWd1SG1oaVE)

As mentioned earlier, I'll try to look into it, for now I just posted it here.

Cheers

**Comment by reilem** [comment]
Is this when you scroll up and keep scrolling up? Does this space "bounce" back or does it stay?

**Comment by ezmegy** [comment]
Oops, sorry, it does bounce back. 

I thought some part of it would stay, but that's only because of my other issue with setting the layout to fill the screen and the top bar disappearing.

**Comment by reilem** [comment]
Alright no worries, I've always left on bounce since it makes it feel "iOS"y :P 
But I'll probably make a customisation feature for it in the future.
